apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-java
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: consumer
  template: 
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: image-registry.openshift-image-registry.svc:5000/confluent/consumer-java
        # resources:
        #   limits:
        #     memory: 1300Mi
        #     cpu: "1"
